-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  has_logged_in boolean NOT NULL DEFAULT false,
  security_answers jsonb,
  first_name text NOT NULL,
  last_name text NOT NULL,
  position USER-DEFINED NOT NULL,
  email text NOT NULL UNIQUE,
  phone text,
  phone_extension text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  last_login_at timestamp with time zone,
  user_id uuid NOT NULL,
  CONSTRAINT admin_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT admin_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.admin_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_account_id uuid NOT NULL,
  session_token text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT admin_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT admin_sessions_admin_account_id_fkey FOREIGN KEY (admin_account_id) REFERENCES public.admin_accounts(id)
);
CREATE TABLE public.customer_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  user_type USER-DEFINED NOT NULL DEFAULT 'customer'::user_type,
  first_name text,
  last_name text,
  phone text,
  billing_address_line1 text,
  billing_address_line2 text,
  billing_city text,
  billing_state text,
  billing_postal_code text,
  billing_country text DEFAULT 'US'::text,
  shipping_address_line1 text,
  shipping_address_line2 text,
  shipping_city text,
  shipping_state text,
  shipping_postal_code text,
  shipping_country text DEFAULT 'US'::text,
  use_billing_as_shipping boolean DEFAULT true,
  profile_completed boolean DEFAULT false,
  email_verified boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  customer_id text UNIQUE,
  CONSTRAINT customer_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  category text NOT NULL CHECK (category = ANY (ARRAY['Feature Issue'::text, 'Recommendation'::text, 'Suggest a Feature'::text, 'Report a Bug'::text, 'Performance Issue'::text, 'Design/UI Feedback'::text, 'Other'::text])),
  page_name text,
  description text NOT NULL,
  primary_supporting_image_url text,
  secondary_supporting_image_url text,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_review'::text, 'in_progress'::text, 'resolved'::text, 'closed'::text, 'wont_fix'::text])),
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  admin_notes text,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT feedback_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT feedback_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stripe_product_id text NOT NULL,
  stripe_price_id text NOT NULL,
  product_id uuid NOT NULL,
  price_id uuid NOT NULL,
  stock_quantity integer NOT NULL DEFAULT 0,
  reserved_quantity integer NOT NULL DEFAULT 0,
  available_quantity integer DEFAULT (stock_quantity - reserved_quantity),
  reorder_point integer DEFAULT 10,
  reorder_quantity integer DEFAULT 50,
  minimum_stock_level integer DEFAULT 5,
  sku text UNIQUE,
  barcode text,
  location text,
  cost_per_unit bigint,
  wholesale_price bigint,
  weight numeric,
  dimensions jsonb,
  is_active boolean NOT NULL DEFAULT true,
  is_featured boolean DEFAULT false,
  is_on_sale boolean DEFAULT false,
  total_sales integer DEFAULT 0,
  total_revenue bigint DEFAULT 0,
  last_sold_at timestamp with time zone,
  times_viewed integer DEFAULT 0,
  supplier_name text,
  supplier_sku text,
  supplier_lead_time_days integer,
  notes text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT inventory_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.stripe_products(id),
  CONSTRAINT inventory_price_id_fkey FOREIGN KEY (price_id) REFERENCES public.stripe_prices(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stripe_invoice_id text NOT NULL UNIQUE,
  stripe_customer_id text NOT NULL,
  stripe_subscription_id text,
  amount_due bigint NOT NULL,
  amount_paid bigint,
  amount_remaining bigint,
  currency text NOT NULL DEFAULT 'usd'::text,
  status text NOT NULL,
  invoice_number text,
  hosted_invoice_url text,
  invoice_pdf text,
  created timestamp with time zone NOT NULL,
  due_date timestamp with time zone,
  period_start timestamp with time zone,
  period_end timestamp with time zone,
  paid_at timestamp with time zone,
  billing_reason text,
  description text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT invoices_pkey PRIMARY KEY (id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid NOT NULL,
  invoice_id uuid,
  ordered_on timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  shipped_on timestamp with time zone,
  delivered_on timestamp with time zone,
  product_available boolean NOT NULL DEFAULT true,
  order_number text UNIQUE,
  total_amount bigint,
  currency text DEFAULT 'usd'::text,
  status text NOT NULL DEFAULT 'pending'::text,
  shipping_address_line1 text,
  shipping_address_line2 text,
  shipping_city text,
  shipping_state text,
  shipping_postal_code text,
  shipping_country text,
  tracking_number text,
  carrier text,
  metadata jsonb,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.customer_accounts(id),
  CONSTRAINT orders_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.security_questions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  question_text text NOT NULL UNIQUE,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT security_questions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stripe_prices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stripe_price_id text NOT NULL UNIQUE,
  stripe_product_id text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  currency text NOT NULL DEFAULT 'usd'::text,
  unit_amount bigint,
  unit_amount_decimal text,
  type text NOT NULL,
  billing_scheme text,
  recurring_interval text,
  recurring_interval_count integer,
  recurring_usage_type text,
  recurring_aggregate_usage text,
  tiers jsonb,
  tiers_mode text,
  nickname text,
  lookup_key text,
  tax_behavior text,
  transform_quantity jsonb,
  metadata jsonb,
  created bigint,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT stripe_prices_pkey PRIMARY KEY (id),
  CONSTRAINT stripe_prices_stripe_product_id_fkey FOREIGN KEY (stripe_product_id) REFERENCES public.stripe_products(stripe_product_id)
);
CREATE TABLE public.stripe_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stripe_product_id text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  active boolean NOT NULL DEFAULT true,
  type text,
  unit_label text,
  images ARRAY,
  metadata jsonb,
  statement_descriptor text,
  url text,
  shippable boolean,
  package_dimensions jsonb,
  tax_code text,
  created bigint,
  updated bigint,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT stripe_products_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  subject text NOT NULL,
  message text NOT NULL,
  assigned_to uuid,
  submitted_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  assigned_at timestamp with time zone,
  in_review_at timestamp with time zone,
  completed_at timestamp with time zone,
  admin_notes text,
  resolution text,
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT tickets_pkey PRIMARY KEY (id),
  CONSTRAINT tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT tickets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.admin_accounts(id)
);
